### ISSUE TITLE
Chapter 5 Jupyter Notebook error

### ISSUE THREAD

**Issue by SSJUSA** [PacktPublishing/Hands-On-Machine-Learning-with-scikit-learn-and-Scientific-Python-Toolkits#4]
Hello,

On Windows 10 GPU NVIDIA Chip Laptop computer,

Chapter 05 Jupyter notebook, KNN Digit Cell #38 following code is giving error

# Styling

for i in range(n_neighbors+1):
   
    for spline in axs[i].spines.values():
        linestyle = '-' if i == 0 else '--'
        linewidth = 3 if i == 0 else 1
       
        spline.set_linestyle(linestyle)
        spline.set_linewidth(linewidth)
        spline.set_color('k')

fig.show()

---> 28 for i in range(n_neighbors+1):
     29 
     30     for spline in axs[i].spines.values():

NameError: name 'n_neighbors' is not defined

Please fix this error and update the notebook of this chapter on this Github webpage.

Thanks and best regards,
SSJ

**Comment by gr33ndata** [comment]
Thanks for your feedback. Fixed it now

**Comment by SSJUSA** [comment]
Thank you for fixing the code error.
