### ISSUE TITLE
Chapter 9 Multi Target Calibration note book

### ISSUE THREAD

**Issue by SSJUSA** [PacktPublishing/Hands-On-Machine-Learning-with-scikit-learn-and-Scientific-Python-Toolkits#5]
Hello,

On Windows 10 laptop computer with NVIDIA GPU,
Ch09 Multi Target Calibration note book

I have commented out Cell #9 code 

# This code will throw a `ValueError: bad input shape`
# We will fix that in the next section
# from sklearn.linear_model import SGDRegressor
#  
# rgr = SGDRegressor()
# rgr.fit(x_train, y_train)
# 
# y_pred = rgr.predict(x_test)

and then  
 Cell #28 is giving following error:

clf = GradientBoostingClassifier()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

ValueError                                Traceback (most recent call last)
<ipython-input-28-812cf83af533> in <module>
      2 
      3 clf = GradientBoostingClassifier()
----> 4 clf.fit(x_train, y_train)
      5 y_pred = clf.predict(x_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\_gb.py in fit(self, X, y, sample_weight, monitor)
    415         sample_weight = _check_sample_weight(sample_weight, X)
    416 
--> 417         y = column_or_1d(y, warn=True)
    418         y = self._validate_y(y, sample_weight)
    419 

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     71                           FutureWarning)
     72         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 73         return f(**kwargs)
     74     return inner_f
     75 

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py in column_or_1d(y, warn)
    846     raise ValueError(
    847         "y should be a 1d array, "
--> 848         "got an array of shape {} instead.".format(shape))
    849 
    850 

ValueError: y should be a 1d array, got an array of shape (375, 3) instead.

Please fix this error and update Jupyter notebook file of Chapter 9 Multi Target to this Github web page.

Thanks and best regards,
SSJ

**Comment by gr33ndata** [comment]
This error is intentional. It's to show the need for `MultiOutputRegressor`. It's explained in the book, and I have a warning message above the cell also explaining the expected error.
